### ISSUE TITLE
Does zidoorecorder use video4linux2 (v4l2)?

### ISSUE THREAD

**Issue by fabdrol** [zidootech/zidoorecorder#1]
Dear Zidoo,

We're in love with the new Zidoo X9S. However, in order to be able to fully utilise it in our use case, we need to access the HDMI input in some way. This app does just that, but we're having trouble figuring out how it actually gets the stream. I have some questions, and I hope you can help:
- Does it use video4linux (2)? 
- How is the stream retrieved from the HDMI input device? My best guess so far is `/dev/video250`, but that doesn't seem to work very well
- Would I be able to access the input stream using ffmpeg or VLC, or do we have to for and change the zidoo recorder application?

Thanks in advance

**Comment by zidootech** [comment]
Hi,
   This project is for Zidoo X9, not for Zidoo X9S.  Recording code of X9S will be released in the feature.
   The project developes on Android camera api,  not V4L2.  
   The output of encoded stream can transfer to ffmpeg/VLC.  Yes, you have to modify the application to duplicate the stream to ffmpeg/vlc.

**Comment by fabdrol** [comment]
Ah, okay.. thank you. How does that work? Other apps don't seem to recognise the HDMI as a camera?
